---

- hosts: ELKstack_servers_IP

  vars_prompt:
    - name: "ansible_user"
      prompt: "Enter remote User Name"
      private: no
    - name: "ansible_password"
      prompt: "Enter remote User Password"
      private: yes


  tasks:
  - name: check ansible_user
    fail: msg="ansible_user is not defined"
    when: ansible_user is not defined or ansible_user == ""
  - name: add authorized_key
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

