  - name: install software for join AD
    yum: pkg={{item}} state=present disable_gpg_check=yes
    with_items:
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - sssd
      - samba-common-tools
      - python-pip

  - name: install pexpect with proxy
    pip:
      name: pexpect
      state: present
      extra_args: "--proxy http://{{ proxyserver }}:{{ proxyport }}"
    when: proxyserver != ''
  - name: install pexpect without proxy
    pip:
      name: pexpect
      state: present
    when: proxyserver == ''

  - name: Check if joined domain
    shell: "realm list | grep sssd"
    register: realm_bound
    changed_when: false
    ignore_errors: true

  - expect:
      command: "realm join {{ domainname }} --computer-ou={{ computerou }} --user={{ adminuser }}"
      responses:
        Password for .*: "{{ ad_password }}"
    when: realm_bound|failed

  - name: Change sssd.conf setting use_fully_qualified_names
    lineinfile:
      dest: /etc/sssd/sssd.conf
      regexp: '^use_fully_qualified_names'
      line: 'use_fully_qualified_names = False'
    notify:
      - restart sssd

  - name: Change sssd.conf setting fallback_homedir
    lineinfile:
      dest: /etc/sssd/sssd.conf
      regexp: '^fallback_homedir'
      line: 'fallback_homedir = /home/%d/%u'
    notify:
      - restart sssd

  - name: Change sssd.conf setting append ddns setting
    lineinfile:
      dest: /etc/sssd/sssd.conf
      line: '{{item}}'
    with_items:
      - dyndns_update = true
      - dyndns_refresh_interval = 43200
      - dyndns_update_ptr = true
      - dyndns_ttl = 3600
    notify:
      - restart sssd

